TravelsStore/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using TravelsStore.Models;

namespace TravelsStore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;

        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }

        public IViewComponentResult Invoke()
        {
            return View(cart);
        }

    }
}

TravelsStore/Components/NavigationMenuViewComponent.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using TravelsStore.Models;

namespace TravelsStore.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private ITripRepository repository;

        public NavigationMenuViewComponent(ITripRepository repo)
        {
            repository = repo;
        }
        
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(repository.Trips
                        .Select(x => x.Category)
                        .Distinct()
                        .OrderBy(x => x));
        }
    }
}

TravelsStore/Controllers/CartController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using TravelsStore.Models;
using TravelsStore.Models.ViewModels;

namespace TravelsStore.Controllers
{
    public class CartController : Controller
    {
        private ITripRepository repository;
        private Cart cart;

        public CartController(ITripRepository repo, Cart cartService)
        {
            repository = repo;
            cart = cartService;
        }

        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToActionResult AddToCart(int tripID, string returnUrl)
        {
            Trip trip = repository.Trips
                .FirstOrDefault(p => p.TripID == tripID);

            if (trip != null)
            {
                cart.AddItem(trip, 1);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToActionResult RemoveFromCart(int tripID, string returnUrl)
        {
            Trip trip = repository.Trips
                .FirstOrDefault(p => p.TripID == tripID);

            if (trip != null)
            {
                cart.RemoveLine(trip);
            }

            return RedirectToAction("Index", new { returnUrl });
        }       
    }
}

TravelsStore/Views/Shared/TripSummary.cshtml
@model Trip

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Name
            <span class="badge badge-pill badge-primary" style="float:right">
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h4>
    </div>
    <form id="@Model.TripID" asp-action="AddToCart"
          asp-controller="Cart" method="post">
        <input type="hidden" asp-for="TripID" />
        <input type="hidden" name="returnUrl"
               value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text p-1">
            @Model.Description
            <button type="submit"
                    class="btn btn-success btn-sm pull-right" style="float:right">
                Add To Cart
            </button>
        </span>
    </form>
</div>

TravelsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="/lib/bootstrap/dist/**/*.min.css" asp-href-exclude="**/*-reboot*,**/*-grid" />
    <link rel="stylesheet" asp-href-include="/lib/fontawesome/css/*.css"/>
    <title>SportsStore</title>
</head>
<body>
    <div class="navbar navbar-inverse bg-inverse" role="navigation">
        <div class="row">
            <a class="col navbar-brand" href="#">TRAVELS STORE</a>
            <div class="col-4 text-right">
                @await Component.InvokeAsync("CartSummary")
            </div>
        </div>
    </div>
    <div class="row m-1 p-1">
        <div id="catergories" class="col-3">
            @await Component.InvokeAsync("NavigationMenu")
        </div>    
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>